DROP SEQUENCE GT_USER_SEQ;
DROP SEQUENCE GT_TAG_SEQ;
DROP TABLE GT_TAGS;
DROP TABLE GT_USERS;

CREATE TABLE GT_USERS(
    USER_ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    FB_ID VARCHAR(50) UNIQUE NOT NULL,
    FCM_TOKEN VARCHAR(200) NOT NULL
);

CREATE TABLE GT_TAGS(
    TAG_ID INTEGER PRIMARY KEY NOT NULL,
    TAG_BODY TEXT NOT NULL,
    SET_FOR_ID VARCHAR(50) NOT NULL,
    SET_BY_ID VARCHAR(50) NOT NULL,
    LATITUDE DECIMAL(10, 6) NOT NULL,
    LONGITUDE DECIMAL(10, 6) NOT NULL
);

ALTER TABLE GT_TAGS ADD CONSTRAINT GT_TAG_SETFOR_FK
FOREIGN KEY (SET_FOR_ID) REFERENCES GT_USERS(FB_ID);

ALTER TABLE GT_TAGS ADD CONSTRAINT GT_TAG_SETBY_FK
FOREIGN KEY (SET_BY_ID) REFERENCES GT_USERS(FB_ID);

CREATE SEQUENCE GT_USER_SEQ INCREMENT 1 START 1;
CREATE SEQUENCE GT_TAG_SEQ INCREMENT 1 START 1;
